In [1]:
import pandas as pd
import re
from datetime import datetime

print('pandas versão:', pd.__version__)
print('Bibliotecas carregadas com sucesso! ')

pandas versão: 2.3.3
Bibliotecas carregadas com sucesso!

In [2]:
CAMINHO = 'C:\\turma-visualizacao-de-dados\\alunos\\andressa_alves\\semana_04\\base_rh.csv'
df = pd.read_csv(CAMINHO, 
                 sep=';',
                 encoding='cp1252',
                 decimal=','
                 )
print('Dados carregados com sucesso! ')
print('Número de linhas e colunas:', df.shape)
print('Número de linhas: ', df.shape[0])
print('Número de colunas: ', df.shape[1])

Dados carregados com sucesso!
Número de linhas e colunas: (1000, 10)
Número de linhas:  1000
Número de colunas:  10

In [3]:
df.head(5)

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
0,1,Julia Nunes,Logística,Coordenador,9088.34,13/08/2024,F,43,Solteiro,Inativo
1,2,Sr. Gustavo Duarte,TI,Gerente,8155.98,29/04/2017,F,59,Solteiro,Inativo
2,3,Srta. Mariana Cunha,RH,Coordenador,14027.93,11/12/2024,F,27,Divorciado,Ativo
3,4,Ana Sophia da Cruz,Produção,Técnico,6647.97,16/06/2019,M,50,Casado,Inativo
4,5,Dr. Nicolas Pinto,Produção,Gerente,8730.19,29/03/2019,F,62,Casado,Inativo

In [4]:
df.tail(10)

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
990,991,Sr. Vicente Silveira,Produção,Gerente,8026.70,11/07/2021,F,55,Viúvo,Inativo
991,992,Emanuel da Cruz,Logística,Gerente,12572.11,30/01/2024,M,33,Viúvo,Ativo
992,993,Enrico Monteiro,RH,Coordenador,14677.33,26/12/2017,M,52,Divorciado,Inativo
993,994,Ana Lívia Cardoso,RH,Coordenador,14912.48,22/10/2015,M,27,Solteiro,Inativo
994,995,Fernando Monteiro,RH,Assistente,10983.02,09/01/2023,F,42,Viúvo,Ativo
995,996,Matheus Aragão,Financeiro,Analista,11389.03,06/05/2022,F,26,Viúvo,Ativo
996,997,Ryan Martins,Financeiro,Analista,14060.42,05/06/2023,F,37,Viúvo,Ativo
997,998,Isabelly Ferreira,TI,Gerente,2348.73,29/12/2023,F,58,Solteiro,Inativo
998,999,Thales Farias,Produção,Analista,9430.62,25/12/2019,M,41,Solteiro,Ativo
999,1000,Sra. Maysa Costela,Produção,Técnico,12549.72,14/11/2022,M,46,Viúvo,Inativo

In [5]:
print('Colunas do DataFrame: ')
print(df.columns.tolist())

Colunas do DataFrame:
['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   object
 2   Departamento    1000 non-null   object
 3   Cargo           1000 non-null   object
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   object
 6   Genero          1000 non-null   object
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   object
 9   Status          1000 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 78.3+ KB

In [7]:
print('Quantidade de valores nulos por coluna: ')
df.isnull().sum()

Quantidade de valores nulos por coluna:

ID_Funcionario    0
Nome              0
Departamento      0
Cargo             0
Salario           0
Data_Admissao     0
Genero            0
Idade             0
Estado_Civil      0
Status            0
dtype: int64

In [8]:
print('Percentual de valores nulos por coluna: ')
print((df.isnull().sum() / len(df)) * 100)

Percentual de valores nulos por coluna:
ID_Funcionario    0.0
Nome              0.0
Departamento      0.0
Cargo             0.0
Salario           0.0
Data_Admissao     0.0
Genero            0.0
Idade             0.0
Estado_Civil      0.0
Status            0.0
dtype: float64

In [9]:
df.describe().round(2)

       ID_Funcionario   Salario    Idade
count         1000.00   1000.00  1000.00
mean           500.50   8579.95    41.40
std            288.82   3657.37    13.67
min              1.00   2000.71    18.00
25%            250.75   5564.54    30.00
50%            500.50   8571.13    41.00
75%            750.25  11554.63    53.00
max           1000.00  14954.51    65.00

In [10]:
print('Valores únicos por coluna: ')
print(df.nunique())

Valores únicos por coluna:
ID_Funcionario    1000
Nome               976
Departamento         6
Cargo                5
Salario           1000
Data_Admissao      878
Genero               2
Idade               48
Estado_Civil         4
Status               2
dtype: int64

In [11]:
for col in ['Departamento','Cargo','Genero','Status','Estado_Civil']:
    print(f'\n --- {col} ---:')
    print(df[col].value_counts())
    print('---')

 --- Departamento ---:
Departamento
Financeiro    189
Produção      182
RH            166
Vendas        160
Logística     156
TI            147
Name: count, dtype: int64
---

 --- Cargo ---:
Cargo
Coordenador    225
Gerente        221
Assistente     199
Analista       178
Técnico        177
Name: count, dtype: int64
---

 --- Genero ---:
Genero
F    510
M    490
Name: count, dtype: int64
---

 --- Status ---:
Status
Ativo      515
Inativo    485
Name: count, dtype: int64
---

 --- Estado_Civil ---:
Estado_Civil
Solteiro      265
Viúvo         261
Divorciado    240
Casado        234
Name: count, dtype: int64
---

In [12]:
df[['Nome','Cargo','Departamento']].head(10)

                   Nome        Cargo Departamento
0           Julia Nunes  Coordenador    Logística
1    Sr. Gustavo Duarte      Gerente           TI
2   Srta. Mariana Cunha  Coordenador           RH
3    Ana Sophia da Cruz      Técnico     Produção
4     Dr. Nicolas Pinto      Gerente     Produção
5         Marcela Costa     Analista           RH
6  João Miguel da Costa      Técnico     Produção
7     Gabrielly Cardoso     Analista           RH
8           Raul da Paz  Coordenador    Logística
9   Davi Lucca Teixeira      Gerente     Produção

In [13]:
df[df['Departamento'] == 'Vendas'][['Nome','Cargo','Departamento','Salario']].head(10)

                     Nome        Cargo Departamento   Salario
12           Laís da Mata     Analista       Vendas   4719.79
26       Cecília Silveira   Assistente       Vendas   5126.11
28  Srta. Ana Lívia Alves  Coordenador       Vendas  14477.24
32          Augusto Jesus   Assistente       Vendas   8686.25
34            Luana Costa  Coordenador       Vendas   5824.04
47          Maitê da Mota  Coordenador       Vendas   7727.77
50           Esther Nunes  Coordenador       Vendas   6506.85
68            Bianca Lima  Coordenador       Vendas   3742.37
70      Luiz Felipe Silva      Gerente       Vendas   2639.39
82      Vinicius da Cunha      Técnico       Vendas   5481.17

In [14]:
ativos = df[df['Status'] == 'Ativo']
print('Total de funcionários: ', len(df))
print('Número de funcionários ativos: ', len(ativos))
print('Número de funcionários inativos: ', len(df) - len(ativos))

Total de funcionários:  1000
Número de funcionários ativos:  515
Número de funcionários inativos:  485

In [15]:
inativos = df[df['Status'] == 'Inativo']
print('Total de funcionários: ', len(df))
print('Número de funcionários ativos: ', len(ativos))
print('Número de funcionários inativos: ', len(inativos))

Total de funcionários:  1000
Número de funcionários ativos:  515
Número de funcionários inativos:  485

In [16]:
gerentes_ti = df[
    (df['Cargo'] == 'Gerente') & (df['Departamento'] == 'TI')
    ]
print('Número de gerentes no departamento de TI: ', len(gerentes_ti))

gerentes_ti[['Nome','Salario','Status', 'Data_Admissao']].head(10)

Número de gerentes no departamento de TI:  31

                   Nome   Salario   Status Data_Admissao
1    Sr. Gustavo Duarte   8155.98  Inativo    29/04/2017
49    Benjamin da Costa   9766.01  Inativo    27/04/2024
130    Catarina Costela   9597.83  Inativo    03/07/2023
131       Laura Cardoso   7364.46  Inativo    29/06/2018
175       Maria Cardoso  12127.27  Inativo    22/05/2024
187   Ana Júlia Cardoso   8738.63    Ativo    30/05/2021
247         Ian Pereira   2395.32    Ativo    10/05/2019
273   Ana Clara Peixoto   7301.14    Ativo    16/11/2019
296      Augusto Santos   8237.80  Inativo    26/08/2021
307     Manuela Barbosa   7015.91    Ativo    21/06/2017

In [17]:
print(f'Salário médio : R$ {df["Salario"].mean():.2f}')
print(f'Salário mínimo : R$ {df["Salario"].min():.2f}')
print(f'Salário máximo : R$ {df["Salario"].max():.2f}')
print(f'Salário mediano : R$ {df["Salario"].median():.2f}')

Salário médio : R$ 8579.95
Salário mínimo : R$ 2000.71
Salário máximo : R$ 14954.51
Salário mediano : R$ 8571.13

In [18]:
import json

df.to_json(
    'base_rh.json', 
    orient='records',
    force_ascii=False, 
    indent=2
    )

print('base_rh.json criada com sucesso!')
df_json = pd.read_json('base_rh.json')
print(f'Linhas lidas do JSON: {len(df_json)}')

with open('base_rh.json', 'r', encoding='utf-8') as f:
    amostra = json.load(f) 

print('\nPrimeiros 2 registros no JSON')
print(json.dumps(amostra[:2], indent=2, ensure_ascii=False))

base_rh.json criada com sucesso!
Linhas lidas do JSON: 1000

Primeiros 2 registros no JSON
[
  {
    "ID_Funcionario": 1,
    "Nome": "Julia Nunes",
    "Departamento": "Logística",
    "Cargo": "Coordenador",
    "Salario": 9088.34,
    "Data_Admissao": "13/08/2024",
    "Genero": "F",
    "Idade": 43,
    "Estado_Civil": "Solteiro",
    "Status": "Inativo"
  },
  {
    "ID_Funcionario": 2,
    "Nome": "Sr. Gustavo Duarte",
    "Departamento": "TI",
    "Cargo": "Gerente",
    "Salario": 8155.98,
    "Data_Admissao": "29/04/2017",
    "Genero": "F",
    "Idade": 59,
    "Estado_Civil": "Solteiro",
    "Status": "Inativo"
  }
]

In [19]:
df.to_excel('base_rh.xlsx', index=False, sheet_name='Funcionarios')
print('base_rh.xlsx (aba única) gerada!')

with pd.ExcelWriter('base_rh_por_departamento.xlsx', engine='openpyxl') as writer:
    df.to_excel(writer, index=False, sheet_name='Todos')
    print('Aba Todos:  todos os registros.')
   
    for depto in sorted(df['Departamento'].unique()):
        df_depto = df[df['Departamento'] == depto]

        nome_aba = depto[:31]  # Limita o nome da aba a 31 caracteres

        df_depto.to_excel(writer, index=False, sheet_name=nome_aba)
        print(f'Aba {nome_aba}: {len(df_depto)} registros.')

print('base_rh_por_departamento.xlsx gerada com abas por departamento!')

base_rh.xlsx (aba única) gerada!
Aba Todos:  todos os registros.
Aba Financeiro: 189 registros.
Aba Logística: 156 registros.
Aba Produção: 182 registros.
Aba RH: 166 registros.
Aba TI: 147 registros.
Aba Vendas: 160 registros.
base_rh_por_departamento.xlsx gerada com abas por departamento!

In [20]:
df_depto.head(10)

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
12,13,Laís da Mata,Vendas,Analista,4719.79,20/12/2019,M,64,Casado,Ativo
26,27,Cecília Silveira,Vendas,Assistente,5126.11,13/10/2022,F,49,Casado,Inativo
28,29,Srta. Ana Lívia Alves,Vendas,Coordenador,14477.24,08/06/2022,F,33,Solteiro,Inativo
32,33,Augusto Jesus,Vendas,Assistente,8686.25,11/07/2021,M,36,Casado,Ativo
34,35,Luana Costa,Vendas,Coordenador,5824.04,29/03/2024,M,21,Casado,Ativo
47,48,Maitê da Mota,Vendas,Coordenador,7727.77,05/02/2018,M,56,Casado,Ativo
50,51,Esther Nunes,Vendas,Coordenador,6506.85,19/01/2016,F,30,Solteiro,Inativo
68,69,Bianca Lima,Vendas,Coordenador,3742.37,24/07/2025,F,33,Divorciado,Ativo
70,71,Luiz Felipe Silva,Vendas,Gerente,2639.39,07/07/2023,M,24,Viúvo,Inativo
82,83,Vinicius da Cunha,Vendas,Técnico,5481.17,18/10/2018,M,48,Casado,Ativo

In [21]:
import locale
0
locale.setlocale(locale.LC_TIME, 'pt_BR.UTF-8')

from datetime import datetime, timedelta

data_texto = '13/08/2024'
data_obj = datetime.strptime(data_texto, '%d/%m/%Y')

print(f'String original : {data_texto}')
print(f'Objeto datetime : {data_obj}')
print(f'Tipo do objeto datetime: {type(data_obj)}')
print()

formatado = data_obj.strftime('%d de %B de %Y')
print(f'Formato: {formatado}')

print(f'Ano: {data_obj.year}')
print(f'Mês: {data_obj.month}')
print(f'Dia: {data_obj.day}')

String original : 13/08/2024
Objeto datetime : 2024-08-13 00:00:00
Tipo do objeto datetime: <class 'datetime.datetime'>

Formato: 13 de agosto de 2024
Ano: 2024
Mês: 8
Dia: 13

In [22]:
hoje = datetime.today()

diferenca = hoje - data_obj

print(f'Data de admissão: {data_texto}')
print(f'Hoje: {hoje.strftime("%d/%m/%Y")}')
print (f'Diferença : {diferenca.days} dias')
print(f'Em anos: {diferenca.days / 365.25:.1f} anos')

Data de admissão: 13/08/2024
Hoje: 12/05/2026
Diferença : 637 dias
Em anos: 1.7 anos

In [23]:
print(f'Tipo antes: {df["Data_Admissao"].dtype}')
print(f'Valor antes: {df["Data_Admissao"].iloc[0]}')
print()

df_limpo = df.copy()

df_limpo['Data_Admissao'] = pd.to_datetime(
    df_limpo['Data_Admissao'], 
    format='%d/%m/%Y', 
    errors='coerce')

print(f'Tipo depois: {df_limpo["Data_Admissao"].dtype}')
print(f'Valor depois: {df_limpo["Data_Admissao"].iloc[0]}')
print(f'NaT gerados: {df_limpo["Data_Admissao"].isna().sum()}')

Tipo antes: object
Valor antes: 13/08/2024

Tipo depois: datetime64[ns]
Valor depois: 2024-08-13 00:00:00
NaT gerados: 0

In [24]:
df_limpo['Ano_Admissão'] = df_limpo['Data_Admissao'].dt.year
df_limpo['Mês_Admissão'] = df_limpo['Data_Admissao'].dt.month
df_limpo['Trimestre'] = df_limpo['Data_Admissao'].dt.quarter

hoje_ts = pd.Timestamp.today()

df_limpo['Tempo_casa_anos'] = (
    (hoje_ts - df_limpo['Data_Admissao']).dt.days / 365.25
).round(1)

cools = ['Nome', 'Data_Admissao', 'Ano_Admissão', 'Mês_Admissão', 'Trimestre', 'Tempo_casa_anos']
df_limpo[cools].head(10)

,Nome,Data_Admissao,Ano_Admissão,Mês_Admissão,Trimestre,Tempo_casa_anos
0,Julia Nunes,2024-08-13,2024,8,3,1.7
1,Sr. Gustavo Duarte,2017-04-29,2017,4,2,9.0
2,Srta. Mariana Cunha,2024-12-11,2024,12,4,1.4
3,Ana Sophia da Cruz,2019-06-16,2019,6,2,6.9
4,Dr. Nicolas Pinto,2019-03-29,2019,3,1,7.1
5,Marcela Costa,2024-07-23,2024,7,3,1.8
6,João Miguel da Costa,2021-11-11,2021,11,4,4.5
7,Gabrielly Cardoso,2022-04-26,2022,4,2,4.0
8,Raul da Paz,2022-11-30,2022,11,4,3.4
9,Davi Lucca Teixeira,2020-06-29,2020,6,2,5.9

In [25]:
def classificar_tempo (anos):
    if pd.isna(anos):
        return 'Sem data'
    elif anos < 1:
        return 'Menos de 1 ano'
    elif anos < 3:
        return '1 a 3 anos'
    elif anos < 5:
        return '3 a 5 anos'
    else:
        return 'Mais de 5 anos'
    
print('Testando a função: ')
print(f'0.5 anos: {classificar_tempo(0.5)}')
print(f'2.1 anos: {classificar_tempo(2.1)}')
print(f'4.8 anos: {classificar_tempo(4.8)}')
print(f'9.0 anos: {classificar_tempo(9.0)}')

Testando a função:
0.5 anos: Menos de 1 ano
2.1 anos: 1 a 3 anos
4.8 anos: 3 a 5 anos
9.0 anos: Mais de 5 anos

In [26]:
df_limpo['Faixa_tempo_casa'] = df_limpo['Tempo_casa_anos'].apply(classificar_tempo)

print('Distribuição por faixa de tempo de casa:')
print(df_limpo['Faixa_tempo_casa'].value_counts())

Distribuição por faixa de tempo de casa:
Faixa_tempo_casa
Mais de 5 anos    539
3 a 5 anos        215
1 a 3 anos        213
Menos de 1 ano     33
Name: count, dtype: int64

In [27]:
hoje = pd.Timestamp.today()

um_ano_atras = hoje - pd.DateOffset(years=1)
cinco_anos_atras = hoje - pd.DateOffset(years=5)

novos_funcionarios = df_limpo[df_limpo['Data_Admissao'] >= um_ano_atras]
veteranos = df_limpo[df_limpo['Data_Admissao'] < cinco_anos_atras]

print(f'Número de novos funcionários (admitidos no último ano (12 meses)): {len(novos_funcionarios)}')
print(f'Número de veteranos (admitidos há mais de 5 anos): {len(veteranos)}')
print()

print('Salário médio:')
print(f'Novos funcionários: R$ {novos_funcionarios["Salario"].mean():.2f}')
print(f'Veteranos: R$ {veteranos["Salario"].mean():.2f}')

Número de novos funcionários (admitidos no último ano (12 meses)): 38
Número de veteranos (admitidos há mais de 5 anos): 534

Salário médio:
Novos funcionários: R$ 8914.83
Veteranos: R$ 8611.31

In [28]:
hoje = pd.Timestamp.today()

um_ano_atras = hoje - pd.DateOffset(months=1)
cinco_anos_atras = hoje - pd.DateOffset(months=5)

novos_funcionarios = df_limpo[df_limpo['Data_Admissao'] >= um_ano_atras]
veteranos = df_limpo[df_limpo['Data_Admissao'] < cinco_anos_atras]

print(f'Número de novos funcionários (admitidos no último ano (12 meses)): {len(novos_funcionarios)}')
print(f'Número de veteranos (admitidos há mais de 5 anos): {len(veteranos)}')
print()

print('Salário médio:')
print(f'Novos funcionários: R$ {novos_funcionarios["Salario"].mean():.2f}')
print(f'Veteranos: R$ {veteranos["Salario"].mean():.2f}')

Número de novos funcionários (admitidos no último ano (12 meses)): 0
Número de veteranos (admitidos há mais de 5 anos): 1000

Salário médio:
Novos funcionários: R$ nan
Veteranos: R$ 8579.95

In [29]:
print('Salário médio por departamento: ')
print(df_limpo
      .groupby('Departamento')['Salario']
      .mean()
      .round(2)
      .sort_values(ascending=False))

Salário médio por departamento:
Departamento
Produção      8968.73
Logística     8881.66
RH            8791.58
Financeiro    8333.12
Vendas        8317.08
TI            8142.91
Name: Salario, dtype: float64

In [30]:
media_depto = (
    df_limpo.groupby('Departamento')['Tempo_casa_anos']
    .mean()
    .round(1)
    .sort_values(ascending=False)
    .rename('Media_Anos')
    .reset_index())

print('Tempo médio de casa por departamento: ')
print(media_depto.to_string(index=False))

maior = media_depto.set_index('Departamento')['Media_Anos'].idxmax()
menor = media_depto.set_index('Departamento')['Media_Anos'].idxmin()

print(f'\n -> Maior retenção: {maior}')
print(f' -> Menor retenção: {menor}')

Tempo médio de casa por departamento:
Departamento  Media_Anos
          RH         5.8
      Vendas         5.7
    Produção         5.5
          TI         5.5
   Logística         5.3
  Financeiro         5.1

 -> Maior retenção: RH
 -> Menor retenção: Financeiro

In [31]:
por_ano = (
    df_limpo
    .groupby('Ano_Admissão')
    .size()
    .rename('Admissoes')
    .reset_index()
    .dropna())

print('Número de admissões por ano: ')
for _, row in por_ano.iterrows():
    barra = '█' * int(row['Admissoes'] / 2)  # Ajusta a escala da barra
    print(f"{int(row['Ano_Admissão'])}: {barra} ({row['Admissoes']:>4})")

Número de admissões por ano:
2015: ████████████████ (  33)
2016: ███████████████████████████████████████████ (  87)
2017: █████████████████████████████████████████████████ (  99)
2018: ████████████████████████████████████████████ (  89)
2019: ██████████████████████████████████████████████████ ( 101)
2020: ███████████████████████████████████████████████ (  94)
2021: ███████████████████████████████████████████████ (  94)
2022: ██████████████████████████████████████████████████████ ( 108)
2023: █████████████████████████████████████████████████████ ( 106)
2024: ████████████████████████████████████████████████████████ ( 113)
2025: ██████████████████████████████████████ (  76)

In [32]:
df_limpo.to_csv('base_rh_dia-01.csv', index=False, sep=';', encoding='utf-8-sig', decimal=',')
print('base_rh_dia-01.csv criada com sucesso!')

print(f'Colunas finais: {df_limpo.columns.tolist()}')
print(f'Linhas finais: {len(df_limpo)}')

base_rh_dia-01.csv criada com sucesso!
Colunas finais: ['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status', 'Ano_Admissão', 'Mês_Admissão', 'Trimestre', 'Tempo_casa_anos', 'Faixa_tempo_casa']
Linhas finais: 1000