## Semana 04 . Dia 1
### base_rh.ipynb
### Aluno: Orlando Vieira de Castro Junior

In [4]:
# Sempre, na primeira célula do notebook, importe as bibliotecas necessárias para a execução do código.

import pandas as pd
import re 
import openpyxl
from datetime import datetime

print("Pandas versão:", pd.__version__)
print("OpenPyXL versão:", openpyxl.__version__)
print("Bibliotecas importadas com sucesso")

Pandas versão: 2.3.3
OpenPyXL versão: 3.1.5
Bibliotecas importadas com sucesso

In [5]:
CAMINHO = "C:/Users/Dell/Documents/GitHub/turma-visualizacao-de-dados/alunos/orlando_castro/semana_04/bases/base_rh.csv"
df = pd.read_csv(
    CAMINHO,
    sep=";",                # separador de campos
    encoding="cp1252",      # encoding para lidar com caracteres acentuados no Windows
    decimal=",")           # separador decimal

print("Dados carregados com sucesso!")
print(f' Número de linhas: {df.shape[0]}')
print(f' Número de colunas: {df.shape[1]}')

Dados carregados com sucesso!
 Número de linhas: 1000
 Número de colunas: 10

In [6]:
df.head(5) #Mostra as 5 primeiras linhas do DataFrame

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
0,1,Julia Nunes,Logística,Coordenador,9088.34,13/08/2024,F,43,Solteiro,Inativo
1,2,Sr. Gustavo Duarte,TI,Gerente,8155.98,29/04/2017,F,59,Solteiro,Inativo
2,3,Srta. Mariana Cunha,RH,Coordenador,14027.93,11/12/2024,F,27,Divorciado,Ativo
3,4,Ana Sophia da Cruz,Produção,Técnico,6647.97,16/06/2019,M,50,Casado,Inativo
4,5,Dr. Nicolas Pinto,Produção,Gerente,8730.19,29/03/2019,F,62,Casado,Inativo

In [7]:
df.tail(5) #Mostra as 5 últimas linhas do DataFrame

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
995,996,Matheus Aragão,Financeiro,Analista,11389.03,06/05/2022,F,26,Viúvo,Ativo
996,997,Ryan Martins,Financeiro,Analista,14060.42,05/06/2023,F,37,Viúvo,Ativo
997,998,Isabelly Ferreira,TI,Gerente,2348.73,29/12/2023,F,58,Solteiro,Inativo
998,999,Thales Farias,Produção,Analista,9430.62,25/12/2019,M,41,Solteiro,Ativo
999,1000,Sra. Maysa Costela,Produção,Técnico,12549.72,14/11/2022,M,46,Viúvo,Inativo

In [8]:
print('Colunas do dataset:')
print(df.columns.tolist())

Colunas do dataset:
['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status']

In [9]:
print('Resumo completo do DataFrame:')
df.info()

Resumo completo do DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   object
 2   Departamento    1000 non-null   object
 3   Cargo           1000 non-null   object
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   object
 6   Genero          1000 non-null   object
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   object
 9   Status          1000 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 78.3+ KB

In [10]:
# df.isnull() → cria uma tabela de True/False (True = é nulo)
# .sum()      → soma os True de cada coluna (True vale 1, False vale 0)
# Resultado: quantidade de nulos por coluna

print("quantidade de registro nulos por coluna:\n", df.isnull().sum())
print()
# Para calcular o percentual de nulos, dividimos a quantidade de nulos pelo total de registros (len(df)) e multiplicamos por 100.
print("Percentual de nulos por coluna:\n", ((df.isnull().sum() / len(df)) * 100).round(2))

quantidade de registro nulos por coluna:
 ID_Funcionario    0
Nome              0
Departamento      0
Cargo             0
Salario           0
Data_Admissao     0
Genero            0
Idade             0
Estado_Civil      0
Status            0
dtype: int64

Percentual de nulos por coluna:
 ID_Funcionario    0.0
Nome              0.0
Departamento      0.0
Cargo             0.0
Salario           0.0
Data_Admissao     0.0
Genero            0.0
Idade             0.0
Estado_Civil      0.0
Status            0.0
dtype: float64

In [11]:
# Estatísticas descritivas para as colunas numéricas, arredondando os valores para 2 casas decimais
print(df.describe().round(2))

       ID_Funcionario   Salario    Idade
count         1000.00   1000.00  1000.00
mean           500.50   8579.95    41.40
std            288.82   3657.37    13.67
min              1.00   2000.71    18.00
25%            250.75   5564.54    30.00
50%            500.50   8571.13    41.00
75%            750.25  11554.63    53.00
max           1000.00  14954.51    65.00

In [12]:
# Identificando colunas categóricas

print('Valores únicos por coluna:')
print(df.nunique())

Valores únicos por coluna:
ID_Funcionario    1000
Nome               976
Departamento         6
Cargo                5
Salario           1000
Data_Admissao      878
Genero               2
Idade               48
Estado_Civil         4
Status               2
dtype: int64

In [13]:
# Loop para contar os valores em cada coluna categórica

for col in ['Departamento', 'Cargo', 'Genero', 'Status', 'Estado_Civil']:
    print(f'Contagem de valores para a coluna "{col}":')
    print(df[col].value_counts())
    print()

Contagem de valores para a coluna "Departamento":
Departamento
Financeiro    189
Produção      182
RH            166
Vendas        160
Logística     156
TI            147
Name: count, dtype: int64

Contagem de valores para a coluna "Cargo":
Cargo
Coordenador    225
Gerente        221
Assistente     199
Analista       178
Técnico        177
Name: count, dtype: int64

Contagem de valores para a coluna "Genero":
Genero
F    510
M    490
Name: count, dtype: int64

Contagem de valores para a coluna "Status":
Status
Ativo      515
Inativo    485
Name: count, dtype: int64

Contagem de valores para a coluna "Estado_Civil":
Estado_Civil
Solteiro      265
Viúvo         261
Divorciado    240
Casado        234
Name: count, dtype: int64

In [14]:
# Selecionar uma coluna e filtras linhas

df['Nome'].head(5) # Mostra os 5 primeiros nomes do DataFrame

0            Julia Nunes
1     Sr. Gustavo Duarte
2    Srta. Mariana Cunha
3     Ana Sophia da Cruz
4      Dr. Nicolas Pinto
Name: Nome, dtype: object

In [26]:
#Selecionar múltiplas colunas
# Note que o primeiro registro tem index 0, então head(5) mostra os registros de index 0 a 4.

df[['Nome', 'Departamento', 'Cargo']].head(5) # Mostra os 5 primeiros registros das colunas Nome, Departamento e Cargo

                  Nome Departamento        Cargo
0          Julia Nunes    Logística  Coordenador
1   Sr. Gustavo Duarte           TI      Gerente
2  Srta. Mariana Cunha           RH  Coordenador
3   Ana Sophia da Cruz     Produção      Técnico
4    Dr. Nicolas Pinto     Produção      Gerente

In [15]:
# Filtrar linhas com base em uma condição (Status == 'Ativo')

ativos = df[df['Status'] == 'Ativo']

print(f'Total de funcionários :{len(df)}')
print(f'Total de funcionários ativos: {len(ativos)}')
print(f'Total de funcionários inativos: {len(df) - len(ativos)}')
print(f'Percentual de funcionários ativos: {(len(ativos) / len(df) * 100):.2f}%')

Total de funcionários :1000
Total de funcionários ativos: 515
Total de funcionários inativos: 485
Percentual de funcionários ativos: 51.50%

In [16]:
# FILTRO COMPOSTO: duas condições ao mesmo tempo
# Use & para AND (as duas condições precisam ser verdadeiras)
# Use | para OR  (pelo menos uma precisa ser verdadeira)
# IMPORTANTE: cada condição precisa estar entre parênteses

gerentes_ti = df[
    (df['Cargo'] == 'Gerente') &
    (df['Departamento'] == 'TI') &
    (df['Status'] == 'Ativo')
]
print(f'Total de gerentes de TI: {len(gerentes_ti)}')
print()
gerentes_ti[['Nome', 'Salario', 'Status', 'Data_Admissao']]

Total de gerentes de TI: 13

                            Nome   Salario Status Data_Admissao
187            Ana Júlia Cardoso   8738.63  Ativo    30/05/2021
247                  Ian Pereira   2395.32  Ativo    10/05/2019
273            Ana Clara Peixoto   7301.14  Ativo    16/11/2019
307              Manuela Barbosa   7015.91  Ativo    21/06/2017
323             Antônio Oliveira   5273.24  Ativo    22/08/2018
414                 Stella Costa  11718.30  Ativo    09/05/2023
422                Bryan da Cruz  11790.21  Ativo    08/02/2021
463            Brenda Nascimento   5429.24  Ativo    25/08/2018
607          Luiz Henrique Souza   4398.17  Ativo    21/11/2015
691  Sra. Maria Fernanda Freitas   2686.67  Ativo    15/09/2019
841                Bernardo Lima   6149.05  Ativo    24/04/2024
891            Ana Clara Moreira  14523.10  Ativo    06/01/2025
927            Valentina Cardoso  10602.13  Ativo    04/06/2023

In [17]:
# Estatísticas rápidas de uma coluna numérica
# .mean()  → média
# .max()   → maior valor
# .min()   → menor valor
# .median()→ mediana (valor do meio quando ordenados)

print(f'Salário médio: R$ {df["Salario"].mean():.2f}')
print(f'Salário máximo: R$ {df["Salario"].max():.2f}')
print(f'Salário mínimo: R$ {df["Salario"].min():.2f}')
print(f'Salário mediana: R$ {df["Salario"].median():.2f}')

Salário médio: R$ 8579.95
Salário máximo: R$ 14954.51
Salário mínimo: R$ 2000.71
Salário mediana: R$ 8571.13

In [18]:
# Exportando o DataFrame para JSON

import json

df.to_json(
    "base_rh.json", 
    orient="records", 
    force_ascii=False, 
    indent=2)

print("DataFrame exportado para base_rh.json com sucesso!")

# Ler o arquivo JSON exportado para verificar o conteúdo
df_json = pd.read_json("base_rh.json")
print(f' Linhas lidas do JSON: {len(df_json)}')

# Ver os 2 primeiros registro do DataFrame lido do JSON
with open("base_rh.json", "r", encoding="utf-8") as f:
    amostra_json = json.load(f)
print('\nPrimeiros 2 registro no JSON:')
print(json.dumps(amostra_json[:2], ensure_ascii=False, indent=2))

DataFrame exportado para base_rh.json com sucesso!
 Linhas lidas do JSON: 1000

Primeiros 2 registro no JSON:
[
  {
    "ID_Funcionario": 1,
    "Nome": "Julia Nunes",
    "Departamento": "Logística",
    "Cargo": "Coordenador",
    "Salario": 9088.34,
    "Data_Admissao": "13/08/2024",
    "Genero": "F",
    "Idade": 43,
    "Estado_Civil": "Solteiro",
    "Status": "Inativo"
  },
  {
    "ID_Funcionario": 2,
    "Nome": "Sr. Gustavo Duarte",
    "Departamento": "TI",
    "Cargo": "Gerente",
    "Salario": 8155.98,
    "Data_Admissao": "29/04/2017",
    "Genero": "F",
    "Idade": 59,
    "Estado_Civil": "Solteiro",
    "Status": "Inativo"
  }
]

In [19]:
# Exportando o DataFrame para Excel
# Antes de executar esta célula, certifique-se de ter a biblioteca openpyxl instalada (pip install openpyxl)

# Se os dados estiverem em uma única aba
df.to_excel("base_rh.xlsx", index=False, sheet_name="Funcionarios")
print("DataFrame exportado para base_rh.xlsx com sucesso!")

# Exportação para Excel com múltiplas abas (uma por departamento)
with pd.ExcelWriter("base_rh_por_depto.xlsx", engine="openpyxl") as writer:

    # Para cada departamento único, cria uma aba com os dados filtrados daquele departamento
    df.to_excel(writer, index=False, sheet_name="Todos")  # Aba com todos os dados
    print('Aba Todos: todos os registro')

    # df['Departamento'].unique() → lista de departamentos sem repetição
    # sorted() → ordena em ordem alfabética
    for depto in sorted(df['Departamento'].unique()):  

        df_depto = df[df['Departamento'] == depto]

        nome_aba = depto[:31]  # Nomes de abas no Excel têm limite de 31 caracteres
        
        df_depto.to_excel(writer, sheet_name=nome_aba,index=False)
        print(f'Aba "{nome_aba}": {len(df_depto)} registro(s) do departamento {depto}')

print("DataFrame exportado para base_rh_por_depto.xlsx com sucesso!")

DataFrame exportado para base_rh.xlsx com sucesso!
Aba Todos: todos os registro
Aba "Financeiro": 189 registro(s) do departamento Financeiro
Aba "Logística": 156 registro(s) do departamento Logística
Aba "Produção": 182 registro(s) do departamento Produção
Aba "RH": 166 registro(s) do departamento RH
Aba "TI": 147 registro(s) do departamento TI
Aba "Vendas": 160 registro(s) do departamento Vendas
DataFrame exportado para base_rh_por_depto.xlsx com sucesso!

In [20]:
# Datatime
# strptime() → converte string para datetime
# strftime() → converte datetime para string

from datetime import datetime

# strptime() → converte string para datetime
data_texto = "15/08/2024"
data_obj = datetime.strptime(data_texto, "%d/%m/%Y")  # '%d/%m/%Y' indica o formato da data (dia/mês/ano)

print(f'String original : "{data_texto}"')
print(f'Objeto datetime : {data_obj})')
print(f'Tipo            : {type(data_obj)}')
print()

# strftime() → converte datetime para string
formatado = data_obj.strftime('%d de %B de %Y')  # Exemplo: '15 de agosto de 2020'
print(f'String formatada: "{formatado}"')

# Extraindo partes da data
print(f'Dia             : {data_obj.day}')
print(f'Mês             : {data_obj.month}') 
print(f'Ano             : {data_obj.year}')

String original : "15/08/2024"
Objeto datetime : 2024-08-15 00:00:00)
Tipo            : <class 'datetime.datetime'>

String formatada: "15 de August de 2024"
Dia             : 15
Mês             : 8
Ano             : 2024

In [21]:
# Timedelta → representa uma duração (diferença entre datas)
from datetime import timedelta
hoje = datetime.today()  # Data e hora atual

diferenca = hoje - data_obj # Subtração entre datetimes resulta em um timedelta

print(f'Data de Adminssão: {data_texto}')
print(f'Data atual       : {hoje.strftime("%d/%m/%Y")}')
print(f'Diferença em dias: {diferenca.days} dias')
print(f'Diferença em anos: {diferenca.days / 365.25:.1f} anos')

Data de Adminssão: 15/08/2024
Data atual       : 13/05/2026
Diferença em dias: 636 dias
Diferença em anos: 1.7 anos

In [22]:
# Convertendo uma coluna inteira para datetime
# Antes de converter posicionar na primeira linha pelo indice (iloc = integer location) 

print(f'Tipo ANTES da conversão: {df["Data_Admissao"].dtype}')
print(f'Valor ANTES da conversão: {df["Data_Admissao"].iloc[0]}')

# Fazer uma cópia do DataFrame para evitar modificar o original
df_limpo = df.copy()

# Converter a coluna "Data_Admissao" para datetime
df_limpo['Data_Admissao'] = pd.to_datetime(
    df_limpo['Data_Admissao'], 
    format="%d/%m/%Y",          # formato da string de entrada
    errors='coerce'             # datas inválidas viram NaT (Not a Time) em vez de gerar erro    
)

print(f'Tipo DEPOIS da conversão: {df_limpo["Data_Admissao"].dtype}')
print(f'Valor DEPOIS da conversão: {df_limpo["Data_Admissao"].iloc[0]}')
print(f'Número de datas inválidas (NaT): {df_limpo["Data_Admissao"].isna().sum()}')

Tipo ANTES da conversão: object
Valor ANTES da conversão: 13/08/2024
Tipo DEPOIS da conversão: datetime64[ns]
Valor DEPOIS da conversão: 2024-08-13 00:00:00
Número de datas inválidas (NaT): 0

In [23]:
# Extraindo informações da data com o acesso ao atributo .dt

# Criar colunas derivadas de data
df_limpo['Ano_Admissao'] = df_limpo['Data_Admissao'].dt.year
df_limpo['Mes_Admissao'] = df_limpo['Data_Admissao'].dt.month
df_limpo['Trimestre'] = df_limpo['Data_Admissao'].dt.quarter

hoje_ts = pd.Timestamp.today()  # Data e hora atual como Timestamp do pandas

df_limpo['Tempo_Casa_Anos'] = (
    (hoje_ts - df_limpo['Data_Admissao']).dt.days / 365.25).round(1)

#Exibe as 5 primeiras linhas do DataFrame com as novas colunas de data
cols = ['Nome', 'Data_Admissao', 'Ano_Admissao', 'Mes_Admissao', 'Trimestre', 'Tempo_Casa_Anos' ]
df_limpo[cols].head(6)

,Nome,Data_Admissao,Ano_Admissao,Mes_Admissao,Trimestre,Tempo_Casa_Anos
0,Julia Nunes,2024-08-13,2024,8,3,1.7
1,Sr. Gustavo Duarte,2017-04-29,2017,4,2,9.0
2,Srta. Mariana Cunha,2024-12-11,2024,12,4,1.4
3,Ana Sophia da Cruz,2019-06-16,2019,6,2,6.9
4,Dr. Nicolas Pinto,2019-03-29,2019,3,1,7.1
5,Marcela Costa,2024-07-23,2024,7,3,1.8

In [24]:
# Criando sua primeira função

def classificar_tempo(anos):
    # pd.isna() verifica se o valor é nulo (NaN ou NaT)
    if pd.isna(anos):
        return 'Sem data'
    elif anos < 1:
        return 'Menos de 1 ano'
    elif anos < 3:
        return '1 a 3 anos'
    elif anos < 5:
        return '3 a 5 anos'
    else:
        return 'Mais de 5 anos'


# Testar a função com valores individuais antes de aplicar no DataFrame
print('Testando a função:')
print(f'  0.5 anos → "{classificar_tempo(0.5)}"')
print(f'  2.1 anos → "{classificar_tempo(2.1)}"')
print(f'  4.8 anos → "{classificar_tempo(4.8)}"')
print(f'  9.0 anos → "{classificar_tempo(9.0)}"')

Testando a função:
  0.5 anos → "Menos de 1 ano"
  2.1 anos → "1 a 3 anos"
  4.8 anos → "3 a 5 anos"
  9.0 anos → "Mais de 5 anos"

In [25]:
# .apply(função) → aplica a função em cada linha da coluna
# Aplica a função classificar_tempo na coluna Tempo_Casa_Anos e cria uma nova coluna Faixa_Tempo_Casa com o resultado

df_limpo['Faixa_Tempo_Casa'] = df_limpo['Tempo_Casa_Anos'].apply(classificar_tempo)

print('Distribuição por faixa de tempo de casa:')
print(df_limpo['Faixa_Tempo_Casa'].value_counts())

Distribuição por faixa de tempo de casa:
Faixa_Tempo_Casa
Mais de 5 anos    540
3 a 5 anos        214
1 a 3 anos        213
Menos de 1 ano     33
Name: count, dtype: int64

In [26]:
# Filtrando por periodo de datas

hoje = pd.Timestamp.today()
um_ano_atras = hoje - pd.DateOffset(years=1)  # Data de um ano atrás
cinco_anos_atras = hoje - pd.DateOffset(years=5)  # Data de cinco anos atrás

#Filtrar por periodo
novos = df_limpo[df_limpo['Data_Admissao'] >= um_ano_atras]
veteranos = df_limpo[df_limpo['Data_Admissao'] < cinco_anos_atras]

print(f'Funcionários admitidos no último ano: {len(novos)}')
print(f'Funcionários admitidos há mais de 5 anos: {len(veteranos)}')

print()

# Comparar salário médio entre os grupos
print('Salário médio:')
print(f'  Novos (último ano)   : R$ {novos["Salario"].mean():.2f}')
print(f'  Veteranos (> 5 anos) : R$ {veteranos["Salario"].mean():.2f}')

Funcionários admitidos no último ano: 38
Funcionários admitidos há mais de 5 anos: 535

Salário médio:
  Novos (último ano)   : R$ 8914.83
  Veteranos (> 5 anos) : R$ 8605.53

In [27]:
# Agrupamentos com groupby() → permite agrupar os dados por uma ou mais colunas e calcular estatísticas para cada grupo

# Salário médio por departamento

print('Salário médio por departamento:')
print(
    df_limpo.groupby('Departamento')['Salario']
    .mean()
    .round(2)
    .sort_values(ascending=False)
)

Salário médio por departamento:
Departamento
Produção      8968.73
Logística     8881.66
RH            8791.58
Financeiro    8333.12
Vendas        8317.08
TI            8142.91
Name: Salario, dtype: float64

In [28]:
# Tempo médio de casa por departamento

media_depto = (
    df_limpo
    .groupby('Departamento')['Tempo_Casa_Anos']
    .mean()
    .round(1)
    .sort_values(ascending=False)
    # rename() → renomeia a série resultante para um nome mais descritivo
    .rename('Media_Anos')  
    .reset_index()         
)

print('Tempo médio de casa por departamento:')
print(media_depto.to_string(index=False))

# .idxmax() → retorna o NOME do índice com maior valor
maior = media_depto.set_index('Departamento')['Media_Anos'].idxmax()
menor = media_depto.set_index('Departamento')['Media_Anos'].idxmin()
print(f'\n→ Maior retenção: {maior}')
print(f'→ Menor retenção: {menor}')

Tempo médio de casa por departamento:
Departamento  Media_Anos
          RH         5.8
      Vendas         5.7
    Produção         5.5
          TI         5.5
   Logística         5.3
  Financeiro         5.1

→ Maior retenção: RH
→ Menor retenção: Financeiro

In [29]:
# Admissões por ano — histórico completo
# .size() → conta o número de linhas em cada grupo
# .sort_index() → ordena pelo índice (neste caso, o ano)

por_ano = (
    df_limpo
    .groupby('Ano_Admissao')
    .size()
    .rename('Admissoes')
    .reset_index()
    .dropna()  # remove linhas com Ano_Admissao nulo
)

print('Admissões por ano:')
for _, row in por_ano.iterrows():
    # .iterrows() → itera linha por linha, retornando (índice, Series)
    # _ → descartamos o índice (convenção: _ = 'não preciso desse valor')
    barra = '█' * int(row['Admissoes'] / 5)
    print(f'  {int(row["Ano_Admissao"])}  {row["Admissoes"]:>4}  {barra}')

Admissões por ano:
  2015    33  ██████
  2016    87  █████████████████
  2017    99  ███████████████████
  2018    89  █████████████████
  2019   101  ████████████████████
  2020    94  ██████████████████
  2021    94  ██████████████████
  2022   108  █████████████████████
  2023   106  █████████████████████
  2024   113  ██████████████████████
  2025    76  ███████████████

In [30]:
# Salvar o DataFrame enriquecido
# encoding='utf-8-sig' → UTF-8 com BOM — necessário para o Excel no Windows
#                         abrir o arquivo sem distorcer ã, é, ç

df_limpo.to_csv(
    'base_rh_dia01.csv',
    index=False,         # não salva o índice numérico como coluna extra
    sep=';',             # separador ponto-e-vírgula
    encoding='utf-8-sig'
)

print('✓ base_rh_dia01.csv salvo!')
print(f'  Colunas finais: {df_limpo.columns.tolist()}')
print(f'  Linhas        : {len(df_limpo)}')

✓ base_rh_dia01.csv salvo!
  Colunas finais: ['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status', 'Ano_Admissao', 'Mes_Admissao', 'Trimestre', 'Tempo_Casa_Anos', 'Faixa_Tempo_Casa']
  Linhas        : 1000

---
## 🏁 CÉLULA 17 — Exercício final

Coloque em prática tudo que você aprendeu hoje.  
Resolva os passos abaixo **nesta célula** (pode criar mais células se quiser).

---

### 🏭 Cenário
O gestor de RH da Indústria Metalúrgica Catarinense pediu 2 entregáveis:
1. A base de funcionários em Excel com **uma aba por departamento**
2. Um relatório de tempo de casa pronto para o Power BI

---

### Passos

**1.** Carregue o `base_rh.csv` com os parâmetros corretos e confirme que `Salario` é `float64`.

**2.** Use `df.info()` e `df.describe()` para fazer o diagnóstico. Anote em uma célula Markdown:  
→ *"Os 3 problemas mais importantes que encontrei foram..."*

**3.** Converta `Data_Admissao` para datetime. Crie as colunas:  
`Ano_Admissao`, `Mes_Admissao`, `Tempo_Casa_Anos` e `Faixa_Tempo_Casa`.

**4.** Responda com `groupby`:  
→ Qual departamento tem a **maior** média de tempo de casa?  
→ Qual tem a **menor**?

**5.** Exporte `base_rh_deptos.xlsx` com uma aba `'Completo'` e mais uma aba por departamento.

**6.** Faça o commit:  
```bash
git pull origin master
git add alunos/seunome/
git commit -m "semana 04 - dia 01: entrega arquivos e datetime"
git push origin master
git log --oneline -3
```
Cole o resultado do `git log` na última célula do notebook.

---

> 💡 **Dica para o Passo 4:**  
> `df.groupby('Departamento')['Tempo_Casa_Anos'].mean().sort_values(ascending=False)`

> ⚠️ **Se o push falhar com 'rejected':** você esqueceu o `git pull` antes.

In [32]:
# ── Resolva o exercício aqui ──────────────────────────────────────────────
import pandas as pd
import re
import openpyxl
import datetime
import json

# Passo 1: carregue o CSV
CAMINHO = "C:/Users/Dell/Documents/GitHub/turma-visualizacao-de-dados/alunos/orlando_castro/semana_04/bases/base_rh.csv"
df = pd.read_csv(
    CAMINHO,
    sep=";",                # separador de campos
    encoding="cp1252",      # encoding para lidar com caracteres acentuados no Windows
    decimal=",")   

print("Dados carregados com sucesso!")
#confirma que Salario é float64
print(f'Tipo da coluna Salario: {df["Salario"].dtype}')

# Passo 2: diagnóstico
print(df.info())
print(df.describe())

# Passo 3: converter datas e criar colunas derivadas
print(f'Tipo ANTES da conversão: {df["Data_Admissao"].dtype}')
print(f'Valor ANTES da conversão: {df["Data_Admissao"].iloc[0]}')

# Fazer uma cópia do DataFrame para evitar modificar o original
df_limpo = df.copy()

# Converter a coluna "Data_Admissao" para datetime
df_limpo['Data_Admissao'] = pd.to_datetime(
    df_limpo['Data_Admissao'], 
    format="%d/%m/%Y",          # formato da string de entrada
    errors='coerce'             # datas inválidas viram NaT (Not a Time) em vez de gerar erro    
)

print(f'Tipo DEPOIS da conversão: {df_limpo["Data_Admissao"].dtype}')
print(f'Valor DEPOIS da conversão: {df_limpo["Data_Admissao"].iloc[0]}')
print(f'Número de datas inválidas (NaT): {df_limpo["Data_Admissao"].isna().sum()}')

# Criar colunas derivadas de data
df_limpo['Ano_Admissao'] = df_limpo['Data_Admissao'].dt.year
df_limpo['Mes_Admissao'] = df_limpo['Data_Admissao'].dt.month

hoje_ts = pd.Timestamp.today()  # Data e hora atual como Timestamp do pandas

df_limpo['Tempo_Casa_Anos'] = (
    (hoje_ts - df_limpo['Data_Admissao']).dt.days / 365.25).round(1)

# Aplica a função classificar_tempo na coluna Tempo_Casa_Anos e cria uma nova coluna Faixa_Tempo_Casa com o resultado
df_limpo['Faixa_Tempo_Casa'] = df_limpo['Tempo_Casa_Anos'].apply(classificar_tempo)

#Exibe as 5 primeiras linhas do DataFrame com as novas colunas de data
cols = ['Nome', 'Data_Admissao', 'Ano_Admissao', 'Mes_Admissao', 'Tempo_Casa_Anos', 'Faixa_Tempo_Casa' ]
df_limpo[cols].head(6)


# Passo 4: groupby — maior e menor média de tempo de casa
# Tempo médio de casa por departamento
media_depto = (
    df_limpo
    .groupby('Departamento')['Tempo_Casa_Anos']
    .mean()
    .round(1)
    .sort_values(ascending=False)
    .rename('Media_Anos')   # .rename() → renomeia a coluna resultante
    .reset_index()          # .reset_index() → converte o índice em coluna comum
)

print('Tempo médio de casa por departamento:')
print(media_depto.to_string(index=False))

maior = media_depto.set_index('Departamento')['Media_Anos'].idxmax()
menor = media_depto.set_index('Departamento')['Media_Anos'].idxmin()
print(f'\n→ Departamento com maior média de tempo de casa: {maior}')
print(f'→ Departamento com menor média de tempo de casa: {menor}')

# Passo 5: exportar df_limpo para Excel

with pd.ExcelWriter('base_rh_deptos.xlsx', engine='openpyxl') as writer:

    # Aba 1: dataset completo
    df_limpo.to_excel(writer, sheet_name='Completo', index=False)
    print('  Aba Completo: todos os registros')

    # df_limpo['Departamento'].unique() → lista de departamentos sem repetição
    # sorted() → ordena em ordem alfabética
    for depto in sorted(df_limpo['Departamento'].unique()):

        # Filtrar só os funcionários desse departamento
        df_depto = df_limpo[df_limpo['Departamento'] == depto]

        # Limite do Excel: nomes de aba têm no máximo 31 caracteres
        nome_aba = depto[:31]

        df_depto.to_excel(writer, sheet_name=nome_aba, index=False)
        print(f'  Aba "{nome_aba}": {len(df_depto)} registros')

print('\n✓ base_rh_deptos.xlsx gerado!')

# Passo 6: cole o output do git log aqui como comentário
# git log:

# PS C:\Users\Dell\Documents\GitHub\turma-visualizacao-de-dados> git log --oneline -3
# 5647045 (HEAD -> master, origin/master, origin/HEAD) Semana 04 - Entrega arquivos e datetime
# 354423b adiciona log no passo 6
# 55b1889 adiciona log no passo 6

Dados carregados com sucesso!
Tipo da coluna Salario: float64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   object
 2   Departamento    1000 non-null   object
 3   Cargo           1000 non-null   object
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   object
 6   Genero          1000 non-null   object
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   object
 9   Status          1000 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 78.3+ KB
None
       ID_Funcionario       Salario        Idade
count     1000.000000   1000.000000  1000.000000
mean       500.500000   8579.951780    41.399000
std        288.819436   3657.365307    13.665817
min          1.000000   2000.710000    18.000000
25%        250.750000   5564.545000    30.000000
50%        500.500000   8571.135000    41.000000
75%        750.250000  11554.630000    53.000000
max       1000.000000  14954.510000    65.000000
Tipo ANTES da conversão: object
Valor ANTES da conversão: 13/08/2024
Tipo DEPOIS da conversão: datetime64[ns]
Valor DEPOIS da conversão: 2024-08-13 00:00:00
Número de datas inválidas (NaT): 0
Tempo médio de casa por departamento:
Departamento  Media_Anos
          RH         5.8
      Vendas         5.7
    Produção         5.5
          TI         5.5
   Logística         5.3
  Financeiro         5.1

→ Departamento com maior média de tempo de casa: RH
→ Departamento com menor média de tempo de casa: Financeiro
  Aba Completo: todos os registros
  Aba "Financeiro": 189 registros
  Aba "Logística": 156 registros
  Aba "Produção": 182 registros
  Aba "RH": 166 registros
  Aba "TI": 147 registros
  Aba "Vendas": 160 registros

✓ base_rh_deptos.xlsx gerado!